# Generated by Django 3.1.5 on 2021-06-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('agent', 'agent')], default='agent', max_length=10),
            preserve_default=False,
        ),
    ]
