# Generated by Django 3.1.5 on 2021-06-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('agent_admin', 'agent_admin'), ('agent', 'agent')], default='agent', max_length=20),
        ),
    ]
