# Generated by Django 3.1.5 on 2021-06-06 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('village', models.CharField(max_length=255)),
                ('mobile_nos', models.CharField(max_length=12)),
                ('landline', models.CharField(blank=True, max_length=12, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('irrigated_farm_area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('non_irrigated_farm_area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('non_farm_land', models.DecimalField(decimal_places=2, max_digits=5)),
                ('co_operative_name', models.CharField(max_length=255)),
                ('step_completed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_stock_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FarmersLiveStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
                ('live_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='FarmersAreaUnderVegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
            ],
        ),
    ]
