# Generated by Django 3.1.5 on 2021-06-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerslivestock',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
