# Generated by Django 3.1.5 on 2021-06-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_farmerslivestock_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mobile_nos',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
