# Generated by Django 3.1.5 on 2021-06-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_farmer_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
