# Generated by Django 3.1.5 on 2021-06-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_auto_20210607_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FarmersAreaUnderVegetable',
            new_name='FarmersCrop',
        ),
    ]
