# Generated by Django 3.1.5 on 2021-06-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_auto_20210607_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerscrop',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
