# Generated by Django 3.1.5 on 2021-06-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_auto_20210607_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='survey_no',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
