# Generated by Django 3.1.5 on 2021-06-09 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_farmer_form_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='form_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
