# Generated by Django 3.1.5 on 2021-06-10 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0010_auto_20210609_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
