# Generated by Django 3.1.5 on 2021-06-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_auto_20210610_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='discard',
            field=models.BooleanField(default=False),
        ),
    ]
