# Generated by Django 3.1.5 on 2021-06-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0012_farmer_discard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='mobile_nos',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='survey_no',
            field=models.CharField(max_length=100),
        ),
    ]
