# Generated by Django 3.1.5 on 2021-06-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0013_auto_20210614_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerscrop',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_crop', to='farmer.crop'),
        ),
        migrations.AlterField(
            model_name='farmerscrop',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_crop', to='farmer.farmer'),
        ),
        migrations.AlterField(
            model_name='farmerslivestock',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_livestock', to='farmer.farmer'),
        ),
        migrations.AlterField(
            model_name='farmerslivestock',
            name='live_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_livestock', to='farmer.livestock'),
        ),
    ]
