# Generated by Django 3.1.5 on 2021-06-19 15:14

from django.db import migrations, models
import farmer.models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0014_auto_20210615_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='form_no',
            field=models.CharField(default=farmer.models.form_number_generator, editable=False, max_length=20, unique=True),
        ),
    ]
