# Generated by Django 3.1.5 on 2021-06-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0015_auto_20210619_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='pin_code',
            field=models.CharField(default=45, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
