# Generated by Django 3.1.5 on 2021-06-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0016_auto_20210620_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='crop_name_mr',
            field=models.CharField(default='नाही ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestock',
            name='live_stock_name_mr',
            field=models.CharField(default='नाही ', max_length=255),
            preserve_default=False,
        ),
    ]
