# Generated by Django 3.1.5 on 2021-06-29 07:42

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0019_auto_20210628_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='last_otp_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 7, 41, 50, 508568, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='farmer',
            name='mobile_nos_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='number_of_otp_retry_allowed',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='farmer',
            name='otp_session_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
