# Generated by Django 3.1.5 on 2021-06-29 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0020_auto_20210629_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='last_otp_generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
